[package]
name = "tabol-rust"
version = "0.1.0"
edition = "2021"
description = "A parser/generator for random table definitions"
repository = ""
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "*"
getrandom = { version = "0.2", features = ["js"] }
nom = "*"
nom-supreme = "0.8.0"
wasm-bindgen = "0.2"
# serde = { version = "1.0", features = ["derive"] }
# serde-wasm-bindgen = "0.4"
web-sys = { version = "0.3.70", features = ["console"] }

[lib]
crate-type = ["cdylib", "rlib"]
